CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS offices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(30),
  address VARCHAR(255),
  description VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(191) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(30),
  phone_normalized VARCHAR(20),
  phone_verified_at TIMESTAMPTZ,
  verified_region_slug VARCHAR(80),
  verified_region_name VARCHAR(120),
  region_verified_at TIMESTAMPTZ,
  location_locked BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_phone_normalized ON users (phone_normalized);

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_id BIGINT REFERENCES offices(id) ON DELETE SET NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'manager' CHECK (role IN ('super', 'manager')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admins_office_id ON admins (office_id);

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_id BIGINT NOT NULL REFERENCES offices(id),
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  listing_title VARCHAR(160) NOT NULL,
  owner_name VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(191),
  property_type VARCHAR(20) NOT NULL CHECK (property_type IN ('apartment', 'officetel', 'villa', 'house', 'commercial', 'land', 'other')),
  transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('sale', 'jeonse', 'monthly', 'consult')),
  address_line1 VARCHAR(255) NOT NULL,
  address_line2 VARCHAR(255),
  postal_code VARCHAR(20),
  region_1depth_name VARCHAR(40),
  region_2depth_name VARCHAR(40),
  region_3depth_name VARCHAR(60),
  region_slug VARCHAR(80),
  latitude NUMERIC(10, 7),
  longitude NUMERIC(10, 7),
  location_verified BOOLEAN NOT NULL DEFAULT FALSE,
  area_m2 NUMERIC(10, 2),
  price_krw BIGINT,
  deposit_krw BIGINT,
  monthly_rent_krw BIGINT,
  move_in_date VARCHAR(50),
  contact_time VARCHAR(100),
  description TEXT,
  admin_memo TEXT,
  privacy_consent BOOLEAN NOT NULL DEFAULT FALSE,
  marketing_consent BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'reviewing', 'completed', 'closed')),
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  published_at TIMESTAMPTZ,
  published_by_admin_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
  view_count INTEGER NOT NULL DEFAULT 0 CHECK (view_count >= 0),
  utm_source VARCHAR(100),
  utm_medium VARCHAR(100),
  utm_campaign VARCHAR(100),
  utm_term VARCHAR(100),
  utm_content VARCHAR(100),
  referrer_url VARCHAR(500),
  landing_url VARCHAR(500),
  user_agent VARCHAR(500),
  submitted_ip VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leads_office_id ON leads (office_id);
CREATE INDEX IF NOT EXISTS idx_leads_user_id ON leads (user_id);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads (status);
CREATE INDEX IF NOT EXISTS idx_leads_is_published ON leads (is_published);
CREATE INDEX IF NOT EXISTS idx_leads_region ON leads (region_2depth_name, region_3depth_name);
CREATE INDEX IF NOT EXISTS idx_leads_region_slug ON leads (region_slug);
CREATE INDEX IF NOT EXISTS idx_leads_transaction_type ON leads (transaction_type);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads (created_at);

CREATE TABLE IF NOT EXISTS lead_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  s3_key VARCHAR(500) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(100) NOT NULL,
  file_size BIGINT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lead_photos_lead_id ON lead_photos (lead_id);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT,
  action_type VARCHAR(100) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT,
  request_ip VARCHAR(64),
  user_agent VARCHAR(500),
  payload_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_admin_id ON audit_logs (admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at);

CREATE TABLE IF NOT EXISTS location_verification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  session_key VARCHAR(120),
  attempted_lat NUMERIC(10, 7) NOT NULL,
  attempted_lng NUMERIC(10, 7) NOT NULL,
  resolved_region_slug VARCHAR(80),
  resolved_region_name VARCHAR(120),
  success BOOLEAN NOT NULL DEFAULT FALSE,
  device_info VARCHAR(500),
  ip_address VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_location_verification_logs_user_id ON location_verification_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_location_verification_logs_region ON location_verification_logs (resolved_region_slug);
CREATE INDEX IF NOT EXISTS idx_location_verification_logs_created_at ON location_verification_logs (created_at);

CREATE TABLE IF NOT EXISTS phone_verification_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verification_key VARCHAR(64) NOT NULL UNIQUE,
  purpose VARCHAR(30) NOT NULL DEFAULT 'signup',
  phone_normalized VARCHAR(20) NOT NULL,
  verification_code VARCHAR(8) NOT NULL,
  request_ip VARCHAR(64),
  user_agent VARCHAR(500),
  expires_at TIMESTAMPTZ NOT NULL,
  verified_at TIMESTAMPTZ,
  consumed_at TIMESTAMPTZ,
  consumed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_phone_verification_lookup ON phone_verification_challenges (phone_normalized, purpose, created_at);
CREATE INDEX IF NOT EXISTS idx_phone_verification_consumed_by ON phone_verification_challenges (consumed_by_user_id);

CREATE TABLE IF NOT EXISTS support_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(160) NOT NULL,
  content TEXT NOT NULL,
  is_secret BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'answered')),
  admin_reply TEXT,
  admin_reply_at TIMESTAMPTZ,
  admin_reply_admin_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
  request_ip VARCHAR(64),
  user_agent VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_support_inquiries_user_id ON support_inquiries (user_id);
CREATE INDEX IF NOT EXISTS idx_support_inquiries_status ON support_inquiries (status);
CREATE INDEX IF NOT EXISTS idx_support_inquiries_created_at ON support_inquiries (created_at);
CREATE INDEX IF NOT EXISTS idx_support_inquiries_admin_reply_admin_id ON support_inquiries (admin_reply_admin_id);

DROP TRIGGER IF EXISTS trg_offices_updated_at ON offices;
CREATE TRIGGER trg_offices_updated_at
BEFORE UPDATE ON offices
FOR EACH ROW
EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS trg_admins_updated_at ON admins;
CREATE TRIGGER trg_admins_updated_at
BEFORE UPDATE ON admins
FOR EACH ROW
EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS trg_leads_updated_at ON leads;
CREATE TRIGGER trg_leads_updated_at
BEFORE UPDATE ON leads
FOR EACH ROW
EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS trg_support_inquiries_updated_at ON support_inquiries;
CREATE TRIGGER trg_support_inquiries_updated_at
BEFORE UPDATE ON support_inquiries
FOR EACH ROW
EXECUTE FUNCTION touch_updated_at();
